import { Timestamp } from 'firebase/firestore';

/* ================================================================
   A single instance of a couple-ritual sit-down. Generated by a
   Cloud Function that reads the couple's shared journal + growth
   state from the last 7 days, then rendered as a guided flow the
   partners walk through together.
   ================================================================ */

export type SessionKind = 'weekInReview' | 'wentWell' | 'wasHard' | 'smallJoys' | 'planAhead';

export interface SessionSection {
  kind: SessionKind;
  /** Short editorial title for the section ("What went well"). */
  title: string;
  /** AI-written opener grounded in the couple's actual week (~2-4 sentences). */
  opener: string;
  /** One sentence that invites the reflection ("Talk about the small win..."). */
  prompt: string;
  /** Optional verbatim snippets pulled from real entries the couple can see. */
  references?: Array<{
    entryId: string;
    snippet: string;
    authorId?: string;
    authorName?: string;
    sourceDate?: string;
  }>;
  /** Shared note the couple types during the section. Saved on every blur. */
  note?: string;
}

export interface RitualIntention {
  /** Plain sentence naming what the couple wants to work on next week. */
  text: string;
  /** Which of the two partners owns moving this forward; null = both. */
  ownerUserId?: string;
}

export type RitualSessionStatus = 'in_progress' | 'complete' | 'abandoned';

export interface RitualSession {
  sessionId: string;
  familyId: string;
  ritualId: string;

  /** Both partners' UIDs. Order-insensitive. */
  participantUserIds: string[];
  /** UID of whoever opened the session. */
  startedByUserId: string;

  sections: SessionSection[];
  intentions: RitualIntention[];

  model: string;
  status: RitualSessionStatus;

  /** Window of entries the opener is grounded in. */
  daysBack: number;

  createdAt: Timestamp;
  generatedAt: Timestamp;
  completedAt?: Timestamp;
}

export const SESSION_COLLECTION = 'ritual_sessions';

export const DEFAULT_SECTION_ORDER: SessionKind[] = [
  'weekInReview',
  'wentWell',
  'wasHard',
  'smallJoys',
  'planAhead',
];
